{ config, pkgs, lib, ... }:

let name = "Ricardo Silva";
    user = "rsilva-freiheit";
    email = "ricardo.silva@freiheit.com"; in
{
  zsh = {
    enable = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;
    enableCompletion = true;
    
    history = {
      size = 10000;
      save = 10000;
      ignoreDups = true;
      extended = true;
    };
    
    shellAliases = {
      ls = "ls --color=auto";
      ll = "ls -la";
      nix-apply = "sudo nix run nix-darwin -- switch --flake ~/.nix-config/.#${pkgs.system}";
      nix-rebuild = "sudo darwin-rebuild switch --flake ~/.nix-config/.#${pkgs.system}";
    };

    # Add hermit shell-hooks
    initContent = ''  
      # Generated by Hermit; START; DO NOT EDIT.
      HERMIT_ROOT_BIN="''${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
      eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
      # Generated by Hermit; END; DO NOT EDIT.
    '';
    
    oh-my-zsh = {
      enable = true;
      plugins = [
        "git"
        "history"
      ];
      theme = "robbyrussell";
    };
  };

  git = {
    enable = true;
    userName = name;
    userEmail = email;
    lfs = {
      enable = true;
    };

    # Configure delta for better diffs
    delta = {
      enable = true;
      options = {
        syntax-theme = "GitHub";
        line-numbers = true;
        navigate = true;
      };
    };

    extraConfig = {
      init.defaultBranch = "main";
      core = {
      editor = "vim";
        autocrlf = "input";
      };
      pull.rebase = true;
      rebase.autoStash = true;
    };
  };
}
