{ config, pkgs, lib, home-manager, dotfiles, user, ... }:
{
  imports = [
    ./dock
    ../../hosts/${user + "@phantom-one"}/home-manager.nix
  ];

  users.users.${user} = {
    name = "${user}";
    home = "/Users/${user}";
    isHidden = false;
    shell = pkgs.zsh;
  };

  # Remove homebrew config from here since it's now in shared/homebrew.nix
  
  environment.systemPackages = import ./system-packages.nix { pkgs = pkgs; };

  home-manager = {
    useGlobalPkgs = true;
    users.${user} = { pkgs, config, lib, ... }:{
      home = {
        enableNixpkgsReleaseCheck = false;
        packages = pkgs.callPackage ../../hosts/${user}-phantom-one/home-packages.nix {};
        stateVersion = "25.05";
      };

      xdg.enable = true;

      # yabai config
      xdg.configFile."yabai/yabairc" = {
        source = "${dotfiles}/yabai/yabairc";
        executable = true;
      };

      # skhd config
      xdg.configFile."skhd/skhdrc" = {
        source = "${dotfiles}/skhd/skhdrc";
        executable = true;
      };
      
      programs = {
        zsh = {
          enable = true;
          autosuggestion.enable = true;
          syntaxHighlighting.enable = true;
          enableCompletion = true;
          
          history = {
            size = 10000;
            save = 10000;
            ignoreDups = true;
            extended = true;
          };
          
          shellAliases = {
            ls = "ls --color=auto";
            ll = "ls -la";
            nix-apply = "sudo nix run nix-darwin -- switch --flake ~/.nix-config/.#${user}@phantom-one";
            nix-rebuild = "sudo darwin-rebuild switch --flake ~/.nix-config/.#${user}@phantom-one";
          };

          # Add hermit shell-hooks
          initExtra = ''  
            # Generated by Hermit; START; DO NOT EDIT.
            HERMIT_ROOT_BIN="''${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
            eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
            # Generated by Hermit; END; DO NOT EDIT.
          '';
          
          oh-my-zsh = {
            enable = true;
            plugins = [
              "git"
              "history"
            ];
            theme = "robbyrussell";
          };
        };
      };
    };
  };

  services.yabai.enable = true ;

  services.skhd.enable = true;



}